### ISSUE TITLE
Additional Parameter are not picked up correctly

### ISSUE THREAD

**Issue by FamularoA** [alanwales/vsts-resharper-code-quality-task#20]
Hello Alan, 

thank you for this extension. I have a question regarding the "Additional arguments" format.

I tried this:

/disable-settings-layers:SolutionPersonal /targets-for-items:"_ResolveInputArguments;DatronLocalization"

But the task fail:

2019-05-23T09:44:02.5049086Z ##[error]Found value /targets-for-items="_ResolveInputArguments;DatronLocalization" with no corresponding named parameter

What is the correct format?

thank you.
Alexander

**Comment by alanwales** [comment]
There was an issue with the escaping so should work now
